### Calculate exercises with correct input
POST http://localhost:3003/exercises
Content-Type: application/json

{
  "daily_exercises": [1, 0, 2, 0, 3, 0, 2.5],
  "target": 2.5
}

### Calculate exercises with missing input
POST http://localhost:3003/exercises
Content-Type: application/json

{
  "target": 2.5
}

### Calculate exercises with malformed input
POST http://localhost:3003/exercises
Content-Type: application/json

{
  "daily_exercises": ["dog", 0, 2, 0, 3, 0, 2.5],
  "target": 2.5
}