### Delete person with ID
DELETE http://localhost:3001/api/persons/1

### Confirm deletion
GET http://localhost:3001/api/persons/1
Accept: application/json

### Add a new person
POST http://localhost:3001/api/persons
Content-Type: application/json

{
  "name": "Bob Bober",
  "number": "123-412897"
}